# Generated by Django 3.0.6 on 2020-11-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('futureyou', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.FileField(upload_to='futureyou/static/files'),
        ),
    ]
